
 // Generated by https://quicktype.io

export interface GetAddress {
    ok:     boolean;
    status: number;
    body:   Address[];
}

export interface Address {
    id:           number;
    Numero:       string;
    Nombre:       string;
    Apellido:     string;
    Nit:          string;
    Direccion:    string;
    Indicacion:   string;
    Tienda:       string;
    Id_usuario:   null | string;
    Pais:         Pais;
    Departamento: string;
    Ciudad:       string;
    Municipio:    null | string;
    email:        string;
    Link_tienda:  string;
}

export enum Pais {
    Gt = "GT",
    Guatemala = "GUATEMALA",
}


