// Generated by https://quicktype.io

export interface GetCombos {
    ok:     boolean;
    status: number;
    body:   Body[];
}

export interface Body {
    ID:         number;
    post_title: string;
    sku:        string;
    price:      string;
    available:  string;
    time_init:  TimeInit;
    time_end:   TimeEnd;
    date_init:  string;
    date_end:   string;
    stock:      Stock;
    img:        string;
    categories: string;
}

export enum Stock {
    Instock = "instock",
    Outofstock = "outofstock",
}

export enum TimeEnd {
    The0601 = "06:01",
    The0701 = "07:01",
    The1200 = "12:00",
    The1300 = "13:00",
    The1315 = "13:15",
    The1501 = "15:01",
    The2100 = "21:00",
    The2300 = "23:00",
    The2359 = "23:59",
}

export enum TimeInit {
    The0600 = "06:00",
    The0700 = "07:00",
    The1130 = "11:30",
    The1200 = "12:00",
    The1800 = "18:00",
}
